spring:
  devtools:
    restart:
      enabled: false # DevTools ?? ??? ????

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/baekjidb
    username: baekji
    password: baekji

  jpa:
    generate-ddl: false # ??? ?? ?? ????
    show-sql: true # ???? SQL? ??
    database: mysql # ?????? ??
    properties:
      hibernate:
        '[format_sql]': true # SQL ?? ? ??? ???

    debug: true # ?? ?? ??? ?? ?? ???
